-- Lead Follow-Up Agent Queue
-- Manages automated follow-up sequences for AI-captured leads

CREATE TABLE IF NOT EXISTS lead_followup_queue (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID REFERENCES dealer_ai_leads(id) ON DELETE CASCADE NOT NULL,
  dealer_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  conversation_id UUID REFERENCES chat_conversations(id) ON DELETE SET NULL,

  -- Follow-up step (1=immediate, 2=day1, 3=day3, 4=day7)
  step INT NOT NULL DEFAULT 1 CHECK (step >= 1 AND step <= 4),

  -- Scheduling
  scheduled_at TIMESTAMPTZ NOT NULL,
  sent_at TIMESTAMPTZ,
  opened_at TIMESTAMPTZ,
  clicked_at TIMESTAMPTZ,

  -- Status
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sending', 'sent', 'failed', 'cancelled', 'skipped')),
  error_message TEXT,

  -- Email content (generated by AI, stored for audit)
  email_subject TEXT,
  email_html TEXT,
  email_to TEXT,

  -- Context for AI generation
  equipment_interest TEXT,
  listing_ids UUID[],
  conversation_summary TEXT,

  -- Tracking
  resend_email_id TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_followup_queue_pending ON lead_followup_queue(scheduled_at)
  WHERE status = 'pending';
CREATE INDEX idx_followup_queue_lead ON lead_followup_queue(lead_id);
CREATE INDEX idx_followup_queue_dealer ON lead_followup_queue(dealer_id);
CREATE INDEX idx_followup_queue_status ON lead_followup_queue(status);

-- RLS
ALTER TABLE lead_followup_queue ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Dealers can view own follow-ups" ON lead_followup_queue
  FOR SELECT USING (auth.uid() = dealer_id);

CREATE POLICY "Service role can manage follow-ups" ON lead_followup_queue
  FOR ALL USING (true) WITH CHECK (true);

-- Update trigger
CREATE TRIGGER trigger_followup_queue_updated_at
  BEFORE UPDATE ON lead_followup_queue
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- Auto-queue follow-ups when a new lead is created
CREATE OR REPLACE FUNCTION queue_lead_followups()
RETURNS TRIGGER AS $$
DECLARE
  v_conversation_summary TEXT;
  v_equipment_interest TEXT;
  v_listing_ids UUID[];
  v_email TEXT;
BEGIN
  -- Only queue if the lead has an email
  IF NEW.visitor_email IS NULL OR NEW.visitor_email = '' THEN
    RETURN NEW;
  END IF;

  v_email := NEW.visitor_email;
  v_equipment_interest := NEW.equipment_interest;

  -- Get conversation summary from messages
  SELECT string_agg(
    CASE WHEN role = 'user' THEN 'Buyer: ' ELSE 'AI: ' END || content,
    E'\n' ORDER BY created_at
  )
  INTO v_conversation_summary
  FROM chat_messages
  WHERE conversation_id = NEW.conversation_id
  LIMIT 20;

  -- Get listing IDs mentioned in the conversation
  SELECT ARRAY_AGG(DISTINCT listing_id)
  INTO v_listing_ids
  FROM chat_conversations
  WHERE id = NEW.conversation_id
    AND listing_id IS NOT NULL;

  -- Step 1: Immediate (within 5 minutes)
  INSERT INTO lead_followup_queue (
    lead_id, dealer_id, conversation_id, step, scheduled_at,
    email_to, equipment_interest, listing_ids, conversation_summary
  ) VALUES (
    NEW.id, NEW.dealer_id, NEW.conversation_id, 1, NOW() + INTERVAL '5 minutes',
    v_email, v_equipment_interest, v_listing_ids, v_conversation_summary
  );

  -- Step 2: Day 1 (24 hours)
  INSERT INTO lead_followup_queue (
    lead_id, dealer_id, conversation_id, step, scheduled_at,
    email_to, equipment_interest, listing_ids, conversation_summary
  ) VALUES (
    NEW.id, NEW.dealer_id, NEW.conversation_id, 2, NOW() + INTERVAL '24 hours',
    v_email, v_equipment_interest, v_listing_ids, v_conversation_summary
  );

  -- Step 3: Day 3 (72 hours)
  INSERT INTO lead_followup_queue (
    lead_id, dealer_id, conversation_id, step, scheduled_at,
    email_to, equipment_interest, listing_ids, conversation_summary
  ) VALUES (
    NEW.id, NEW.dealer_id, NEW.conversation_id, 3, NOW() + INTERVAL '72 hours',
    v_email, v_equipment_interest, v_listing_ids, v_conversation_summary
  );

  -- Step 4: Day 7 (168 hours)
  INSERT INTO lead_followup_queue (
    lead_id, dealer_id, conversation_id, step, scheduled_at,
    email_to, equipment_interest, listing_ids, conversation_summary
  ) VALUES (
    NEW.id, NEW.dealer_id, NEW.conversation_id, 4, NOW() + INTERVAL '168 hours',
    v_email, v_equipment_interest, v_listing_ids, v_conversation_summary
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER auto_queue_lead_followups
  AFTER INSERT ON dealer_ai_leads
  FOR EACH ROW
  EXECUTE FUNCTION queue_lead_followups();

-- Function to cancel remaining follow-ups for a lead
-- (called when buyer responds, unsubscribes, or lead is marked contacted)
CREATE OR REPLACE FUNCTION cancel_lead_followups(p_lead_id UUID)
RETURNS INT AS $$
DECLARE
  v_cancelled INT;
BEGIN
  UPDATE lead_followup_queue
  SET status = 'cancelled', updated_at = NOW()
  WHERE lead_id = p_lead_id
    AND status = 'pending';
  GET DIAGNOSTICS v_cancelled = ROW_COUNT;
  RETURN v_cancelled;
END;
$$ LANGUAGE plpgsql;

COMMENT ON TABLE lead_followup_queue IS 'Automated follow-up email queue for AI-captured leads';
COMMENT ON FUNCTION queue_lead_followups IS 'Auto-queues 4-step follow-up sequence when a new AI lead is captured';
COMMENT ON FUNCTION cancel_lead_followups IS 'Cancels pending follow-ups for a lead (e.g., buyer responded)';
